# Explore here

In [1]:
#pip install streamlit
import pandas as pd
import streamlit as st

df = pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/121/280/Pokemon.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20240623%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240623T224628Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=8188350d38140147125ed149183191e900c39f7f583ce939bbbef7ef66694b193445ac4fef02130a621fb6553d28335f83fcf706098b4c429f6b1d37ffcce3865f1afde6e3d218756e8d530705156a4925431280c7e35156b482d34bbdcaa8026660422a50c695a20c211b6b423849bb8532bdc708611b73b59613b757a52799e0fb77060ad5f0c37ae52674946553c81dbb8b7242d61b5c660d217bd791a029dab15e8005fa9a4aff3d5575ee6dc7d0a381abf9cc486de5856ba973598bd09368868225c3d573bce67b0523b1846a7b099a11abf2a1e43dc0ad67bdef10610446dc85bdd675c7beba32e1ac3ec5ef187aef549d271133702f2569dfa3f4dd1d')
df.to_csv('../data/raw/pokemon_data_raw.csv', index=False)
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [3]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [4]:
df.sort_values(by='Legendary')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
512,461,Weavile,Dark,Ice,510,70,120,65,45,85,125,4,False
513,462,Magnezone,Electric,Steel,535,70,70,115,130,90,60,4,False
514,463,Lickilicky,Normal,NaN,515,110,85,95,80,95,50,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,386,DeoxysSpeed Forme,Psychic,NaN,600,50,95,90,95,90,180,3,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
425,384,Rayquaza,Dragon,Flying,680,105,150,90,150,90,95,3,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [8]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#Usar la suma de las caracteristicas ('total') para predecir la tasa de crecimiento ('growth_rate')
caracteristicas = df[['Total','HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']]
pokeresultado = df['Legendary']

X_train, X_test, y_train, y_test = train_test_split(caracteristicas, pokeresultado, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelo_regrlog = LogisticRegression(max_iter=1000)

modelo_regrlog.fit(X_train_scaler, y_train)

y_pred = modelo_regrlog.predict(X_test_scaler)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.94375

In [11]:
#Guardado del modelo Random Forest ('modelo_bosque')
from pickle import dump

dump(modelo_regrlog, open("../models/logistic_regression_default_42.sav", "wb"))

In [12]:
import sklearn
print(sklearn.__version__)

1.2.2